### ISSUE TITLE
miyoo mini plus support?

### ISSUE THREAD

**Issue by ahahahaah** [jhe2/gmu#11]
hello i wanted to install gmu in the miyoo mini plus but when i want to play any mp3, instead of the song title i have the message "cannot open audio device".

not sure if it is compatible with myoo mini plus since the installation instructions 
https://github.com/TechDevangelist/gmu/releases 
talk about "Extract MiniUI-Gmu.zip contents into the Tools folder on your SD card" but there is no tools folder but emu folder, so i created a tools folder to place the zip content and extract also to the emu folder but i'm not sure that it is the way to go.
in my opinion the codec files in the decoders folder of the app are not accessed.

i have found some comments on forums about the same error and every time nobody answer them.
thanks for your help

**Comment by jhe2** [comment]
Since I do not have a Myoo Mini Plus myself, unfortunately I can't tell you exactly what to do to get it to run. Since you are trying to use TechDevangelist's fork of Gmu and that fork appears to be created for a similar device to yours, TechDevangelist might know the difference between the two devices and can possibly give you a hint on what to do. Try opening a bug on TechDevangelist's repository for such device specific issues.

**Comment by ahahahaah** [comment]
if you are talking about this page https://github.com/TechDevangelist/gmu there is no "issues" tab.
i tryed to contact him but there is no way to this.
do you have an idea to reach him? 
thanks

**Comment by jhe2** [comment]
> do you have an idea to reach him?

No, sorry.
