### ISSUE TITLE
gme pluging code?

### ISSUE THREAD

**Issue by Ninoh-FOX** [jhe2/gmu#13]
**Describe the bug**
I've tried to put the gme.so plugin in the program but I don't know how to make it recognize the formats, you just see a blank list and if I put them as m3u it doesn't play any

**System (please complete the following information):**
 - Hardware: Miyoo Mini

**Comment by jhe2** [comment]
Since I don't know anything about the gme.so plugin, I can only speculate here.

One thing you should check is which file extensions are actually recognized by the plugin. Decoder plugins tell Gmu which file types they are capable of handling (via a list of file extensions). Gmu will then use that information to decide which file types it is able to play. If the plugin doesn't announce the extensions you expect, the files won't show up.

The only other reason I can think of why certain files don't show up in Gmu, is if the plugin supporting those file types hasn't actually been loaded. So you should make sure the plugin has been loaded successfully. Gmu's about screen lists all loaded plugins, so this is easy to verify.

If it hasn't been loaded, I'm afraid there is not much I can do, without any more information. There could be various reasons for that, e.g. a missing library that the plugin itself depends on. The plugin author would probably be in a better position to diagnose the problem. Is the source of the gme plugin publicly available?

**Comment by Ninoh-FOX** [comment]
I am compile the code with the extensions, but I don't know if this load the codec, only pass to the next file.

In my github:

https://github.com/Ninoh-FOX/gme

**Comment by jhe2** [comment]
The link you supplied looks like the source code to a library that supports decoding of some game music file formats. While this could be used to build a plugin for Gmu so Gmu can play such files, the library itself does not come with a Gmu-compatible plugin, as far as I can tell. The glue code needed for a Gmu decoder plugin is rather simple, so it shouldn't be too difficult to implement one.

Unless I am missing something, this can't possibly work with just the code you've linked to. I didn't look at the entire source, so if you know there is a Gmu decoder plugin included, please point me to the exact source file, so I can have a look.

**Comment by Ninoh-FOX** [comment]
No.  I really didn't know that a linker was needed, I thought it was worth putting the formats and the libraries, so I don't have the code you say.

**Comment by jhe2** [comment]
No worries. Just in case you are interested, it is not so much about the linker but rather the API that the .so needs to implement so that Gmu know what to do with it. That basically means that the .so file needs to implement a function with a specific name that acts as an entry point for Gmu so that it can initialize the plugin and use it.
For anyone who wants to implement a decoder plugin for Gmu, I'd recommend having a look at any of Gmu's included decoders, e.g. the mpg123 decoder plugin. It is rather simple.

Anyway, I'll close this issue since it isn't really a bug in Gmu.

**Comment by Ninoh-FOX** [comment]
Thanks
