### ISSUE TITLE
MP3 playback is broken

### ISSUE THREAD

**Issue by pcercuei** [jhe2/gmu#4]
The mpg123.so decoder segfaults when trying to play a MP3 file.

I assume it's not a OS or MP3 file problem, since the same MP3 file plays file with the "mpg123" program.

**Comment by jhe2** [comment]
Do you have some more details about the system (CPU architecture, operating system, etc.) where the problem occurs? It works fine on the systems I have tested it on. Depending on the target CPU, libmpg123 needs to be compiled with the appropriate flags, e.g. when running on a CPU without an FPU, the fixed-point code needs to be enabled.

**Comment by pcercuei** [comment]
@jhe2 it's running on a RetroMini RS-90, the CPU is somewhat similar to what was in the Dingoo A320. The OS is Linux (OpenDingux). I assume that if the "mpg123" binary can play back correctly then it's not a libmpg123 problem.

I can debug it further when I find some time.

**Comment by jhe2** [comment]
You are right, if mpg123 uses the same libmpg123 as was used with Gmu, this shouldn't be the issue. I haven't recently run Gmu on a MIPS device, maybe I can check that. I assume you are using a fairly recent libmpg123 version?

**Comment by pcercuei** [comment]
I use mpg123 1.25.13.

**Comment by adam820** [comment]
Hello! As noted in the referenced mention, I'm trying to get gmu running on an Anbernic RG350M. The Adam image uses OpenDingux Beta underneath, CPU is JZ4770 Dual-Core 64Bit – 1.00Ghz. I'm able to play FLAC and Opus no problem, but MP3 does nothing and halts all further playback; I get the following in the output:

`/media/sdcard/apps/gmu-0.10.1-rg350m/gmu.bin: can't resolve symbol 'mpg123_set_filesize'`

Is this maybe a library version mismatch?

**Comment by jhe2** [comment]
> Is this maybe a library version mismatch?

Yes, that does indeed look like a version mistmatch with the libmpg123 library. Since you were able to build Gmu, but it fails at runtime with this error, the build environment and the runtime environment on the device must differ. Usually, this should be avoided. You could try to copy the libmpg123.so.* files from your build environment onto the device (and if necessary adjust/set the ``LD_LIBRARY_PATH`` accordingly), to see if it fixes the problem.

I'm not sure if this is the same issue that pcercuei has, though.

**Comment by jhe2** [comment]
Probably fixed by commits b1d75251bc3971e78e2e0450daa2b610c7f19da7 and d46c3b2205c6e4181191de8ae0399b2fa1342bed.
